const productAttributesObj = {
  condition: ["Used, Good"],
  height: ["0.00"],
  width: ["0.00"],
  length: ["0.00"],
  size: ["XL"],
  color: ["Blue", "Red"],
  closure: ["Pullover"],
  season: ["All Seasons"],
  sizeType: ["Regular"],
  department: ["Women"],
  style: ["Cropped"],
  neckline: ["Round Neck"],
  sleeveLength: ["Long Sleeve"],
  pattern: ["Striped"],
  theme: ["Modern"],
  fit: ["Regular"],
  occasion: ["Casual"],
  features: ["Comfort"],
  type: ["Blouse"],
};
